services:
  database:
    image: postgres:15.8
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/script.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - internal

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      PORT: 3000
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: postgres
    depends_on:
      - database
    command: ["dockerize", "-wait", "tcp://database:5432", "-timeout", "60s", "node", "index.js"]
    networks:
      - internal

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    networks:
      - external

  proxy:
    build: ./proxy
    container_name: proxy
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
    networks:
      - external
      - internal

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge
  external:
    driver: bridge
